{{- $group := "external-dns.acme.cert-manager.io" -}}
{{- $version := "v1alpha1" -}}
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: {{ $version }}.{{ $group }}
  labels:
    {{- include "acme-webhook-external-dns.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ include "acme-webhook-external-dns.name" . }}"
spec:
  group: {{ $group }}
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: {{ include "acme-webhook-external-dns.name" . }}
    namespace: {{ .Release.Namespace }}
  version: {{ $version }}