{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "acme-webhook-external-dns.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "acme-webhook-external-dns.labels" . | nindent 4 }}
spec:
  {{- include "acme-webhook-external-dns.pdb.spec" .Values.podDisruptionBudget | nindent 2 }}
  selector:
    matchLabels:
      app: {{ include "acme-webhook-external-dns.name" . }}
{{- end -}}