apiVersion: v1
kind: Service
metadata:
  name: {{ include "acme-webhook-external-dns.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "acme-webhook-external-dns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: {{ include "acme-webhook-external-dns.name" . }}